version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: avatartour-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__AvatarTourSystem=Server=sql;Database=AvatarTourSystemDB;User=sa;Password=09098712aA;TrustServerCertificate=True;
    depends_on:
      - sql
    networks:
      - app-network

  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: avatartour-sql
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=09098712aA
    volumes:
      - sql-data:/var/opt/mssql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    #restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  sql-data:
