# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore ./AvatarTourSystem_BE/AvatarTourSystem_BE/AvatarTourSystem_BE.csproj
    - name: Build
      run: dotnet build ./AvatarTourSystem_BE/AvatarTourSystem_BE/AvatarTourSystem_BE.csproj
